apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretsManagerStoreName }}
    kind: ClusterSecretStore
  target:
    name: db-secret
    creationPolicy: Owner
  data:
  - secretKey: DB_USERNAME
    remoteRef:
      key: {{ .Values.externalSecrets.dbSecretName }}
      property: username
  - secretKey: DB_PASSWORD
    remoteRef:
      key: {{ .Values.externalSecrets.dbSecretName }}
      property: password
  - secretKey: DB_ENDPOINT
    remoteRef:
      key: {{ .Values.externalSecrets.dbSecretName }}
      property: host
  - secretKey: DB_PORT
    remoteRef:
      key: {{ .Values.externalSecrets.dbSecretName }}
      property: port
