apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "colorapp.fullname" . }}
  labels:
    {{- include "colorapp.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /colorapp
        pathType: Prefix
        backend:
          service:
            name: {{ include "colorapp.fullname" . }}
            port:
              name: http